# site properties and page defaults
title: CHIEN LAB
subtitle: Biosystem IC devices
description: Our group's research focuses on integrated circuits and their convergence with bio- and quantum technologies. We are dedicated to creating sensors and devices for point-of-care diagnostics and emphasizing continuous monitoring through wearables, implantable devices, injectables, and swallowables. Additionally, we explore millimeter-wave ICs for communication, sensing, and interfaces for qubits. Please come talk to us if you’re interested in!
header: images/background_white.png
footer: images/background.png

# site social media and other links
links:
  email: chienlab521@gmail.com
  #orcid: 
  google-scholar: https://scholar.google.com/citations?user=r5b2ufgAAAAJ&hl=en
  #github: 
  #twitter: 
  #youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
