# JOURNAL
- id: doi:10.1109/LMWC.2005.856848
  tags:
  - type: journal
  
- id: doi:10.1109/LMWC.2006.882383
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2007.894819
  tags:
  - type: journal
  
- id: doi:10.1109/TMTT.2007.902071
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2007.903058
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2007.903050
  tags:
  - type: journal
 
- id: doi:10.1109/LMWC.2007.905634
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2007.908688
  tags:
  - type: journal
  
- id: doi:10.1021/nl2043375
  tags:
  - type: journal
  
- id: doi:10.1021/nl301699k
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2010.2077150
  tags:
  - type: journal
  
- id: doi:10.1109/TMTT.2014.2345342
  tags:
  - type: journal
  
- id: doi:10.1109/TMTT.2015.2407356
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2015.2500362
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2016.2573300
  tags:
  - type: journal
  
- id: doi:10.1039/C8LC00299A
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2019.2951691
  tags:
  - type: journal
  
- id: doi:10.1109/JSSC.2020.3020789
  tags:
  - type: journal
  
- id: doi:10.1002/adma.202109764
  tags:
  - type: journal
  
- id: doi:10.1109/LMWT.2023.3265584
  tags:
  - type: journal
  
- id: doi:10.1021/acssensors.3c00509
  tags:
  - type: journal
  
# CONFERENCE
- id: 10.1109/IEDM50854.2024.10873317
  tags:
  - type: conference

- id: doi:10.1109/CICC.2005.1568622
  tags:
  - type: conference
  
- id: doi:10.1109/ASSCC.2005.251702
  tags:
  - type: conference
  
- id: doi:10.1109/VLSIC.2006.1705352
  tags:
  - type: conference
  
- id: doi:10.1109/VLSIC.2006.1705368
  tags:
  - type: conference
  
- id: doi:10.1109/ISSCC.2007.373535
  tags:
  - type: conference
  
- id: doi:10.1109/JSSC.2007.908688
  tags:
  - type: conference
  
- id: doi:10.1109/ISSCC.2010.5433852
  tags:
  - type: conference
  
- id: doi:10.1109/RFIC.2011.5940606
  tags:
  - type: conference
  
- id: doi:10.1109/RFIC.2011.5940672
  tags:
  - type: conference
  
- id: doi:10.1109/JSSC.2013.2239004
  tags:
  - type: conference
  
- id: doi:10.1109/MWSYM.2013.6697466
  tags:
  - type: conference
  
- id: doi:10.1109/RFIC.2014.6851712
  tags:
  - type: conference
  
- id: doi:10.1109/ISSCC.2014.6757334
  tags:
  - type: conference
  
- id: doi:10.1109/JSSC.2016.2621036
  tags:
  - type: conference
  
- id: doi:10.1109/MWSYM.2014.6848507
  tags:
  - type: conference
  
- id: doi:10.1109/VLSIC.2014.6858408
  tags:
  - type: conference

- id: doi:10.1109/MWSYM.2015.7166871
  tags:
  - type: conference
  
- id: doi:10.1109/ARFTG.2015.7162910
  tags:
  - type: conference
  
- id: doi:10.1109/MWSYM.2015.7167141
  tags:
  - type: conference
  
- id: doi:10.1109/VLSIC.2015.7231312
  tags:
  - type: conference
  
- id: doi:10.1109/ARFTG.2015.7381458
  tags:
  - type: conference
  
- id: doi:10.1109/MWSYM.2017.8058717
  tags:
  - type: conference
  
- id: doi:10.1109/SIRF.2018.8304233
  tags:
  - type: conference
  
- id: doi:10.1109/MWSYM.2018.8439332
  tags:
  - type: conference
  
- id: doi:10.1109/VLSIC.2018.8502293
  tags:
  - type: conference
  
- id: doi:10.1109/CICC.2019.8780179
  tags:
  - type: conference
  
- id: doi:10.23919/VLSIC.2019.8777991
  tags:
  - type: conference
  
- id: doi:10.1109/ISSCC19947.2020.9063036
  tags:
  - type: conference
  
- id: doi:10.1109/ARFTG54656.2022.9896578
  tags:
  - type: conference
  
- id: doi:10.1109/RFIC54546.2022.9863095
  tags:
  - type: conference
  
- id: doi:10.1109/VLSITechnologyandCir46769.2022.9830290
  tags:
  - type: conference
  
- id: doi:10.1109/BioCAS54905.2022.9948586
  tags:
  - type: conference
  
- id: doi:10.1109/MEMS49605.2023.10052329
  tags:
  - type: conference
  
- id: doi:10.1109/IMS37964.2023.10188078
  tags:
  - type: conference
  
- id: doi:10.23919/VLSITechnologyandCir57934.2023.10185383
  tags:
  - type: conference
  

# OTHERS
- id: google.patent:US8841948B1
  tags:
  - type: patent

- id: google.patent:US11083388B2
  tags:
  - type: patent
