# JOURNAL
- id: doi:10.1109/LMWC.2005.856848
  type: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7260/32380/1512219/1512219-fig-3-source-large.gif

- id: doi:10.1109/LMWC.2006.882383
  type: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7260/35974/1704863/1704863-fig-4-source-large.gif

- id: doi:10.1109/JSSC.2007.894819
  type: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/4160057/4160073/4160073-fig-2-source-large.gif

- id: doi:10.1109/TMTT.2007.902071
  type: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/22/4287157/4287160/4287160-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2007.903058
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/4295179/4295184/4295184-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2007.903050
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/4295179/4295183/4295183-fig-1-source-large.gif

- id: doi:10.1109/LMWC.2007.905634
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7260/4336131/4336133/4336133-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2007.908688
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/4381435/4381440/4381440-fig-1-source-large.gif

- id: doi:10.1021/nl2043375
  group: journal
  image: https://pubs.acs.org/cms/10.1021/nl2043375/asset/images/medium/nl-2011-043375_0006.gif

- id: doi:10.1021/nl301699k
  group: journal
  image: https://pubs.acs.org/cms/10.1021/nl301699k/asset/images/medium/nl-2012-01699k_0001.gif

- id: doi:10.1109/JSSC.2010.2077150
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/5625049/5604327/5604327-fig-1-source-large.gif

- id: doi:10.1109/TMTT.2014.2345342
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/22/6915782/6878492/6878492-fig-2-source-large.gif

- id: doi:10.1109/TMTT.2015.2407356
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/22/7078974/7056563/7056563-fig-2-source-large.gif

- id: doi:10.1109/JSSC.2015.2500362
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/7398196/7361982/chien1ab-2500362-large.gif

- id: doi:10.1109/JSSC.2016.2573300
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/7526339/7501825/chien1-2573300-large.gif

- id: doi:10.1039/C8LC00299A
  group: journal
  image: https://pubs.rsc.org/image/article/2018/lc/c8lc00299a/c8lc00299a-f1_hi-res.gif
  
- id: doi:10.1109/JSSC.2019.2951691
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/9011683/8910390/chien1ab-2951691-large.gif

- id: doi:10.1109/JSSC.2020.3020789
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/9237188/9198904/chien1ab-3020789-large.gif

- id: doi:10.1002/adma.202109764
  group: journal
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9793805/bin/nihms-1855823-f0006.jpg

- id: doi:10.1109/LMWT.2023.3265584
  group: journal
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9944983/10144809/10106051/chien1ab-3265584-large.gif

- id: doi:10.1021/acssensors.3c00509
  group: journal
  image: https://pubs.acs.org/cms/10.1021/acssensors.3c00509/asset/images/medium/se3c00509_0009.gif

# CONFERENCE
- id: doi:10.1109/CICC.2005.1568622
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/10489/33245/1568622/1568622-fig-1-source-large.gif

- id: doi:10.1109/ASSCC.2005.251702
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4017511/4017512/4017568/4017568-fig-1-source-large.gif

- id: doi:10.1109/VLSIC.2006.1705352
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/11174/35987/1705352/1705352-fig-1-source-small.gif

- id: doi:10.1109/VLSIC.2006.1705368
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/11174/35987/1705368/1705368-fig-1-source-large.gif

- id: doi:10.1109/ISSCC.2007.373535
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4242240/4242241/4242506/4242506-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2007.908688
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/4381435/4381440/4381440-fig-1-source-large.gif

- id: doi:10.1109/ISSCC.2010.5433852
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/5428240/5433812/5433852/5433852-fig-1-source-large.gif

- id: doi:10.1109/RFIC.2011.5940606
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/5930383/5940585/5940606/5940606-fig-1-source-large.gif

- id: doi:10.1109/RFIC.2011.5940672
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/5930383/5940585/5940672/5940672-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2013.2239004
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/6484888/6484917/6484917-fig-1-source-large.gif

- id: doi:10.1109/MWSYM.2013.6697466
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/6684335/6697324/6697466/6697466-fig-1-source-large.gif

- id: doi:10.1109/RFIC.2014.6851712
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/6844558/6851613/6851712/6851712-fig-1-source-large.gif

- id: doi:10.1109/ISSCC.2014.6757334
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/6747109/6757318/6757334/6757334-fig-1-source-large.gif

- id: doi:10.1109/JSSC.2016.2621036
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/4/7845730/7762853/mural2-2621036-large.gif

- id: doi:10.1109/MWSYM.2014.6848507
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/6842514/6847849/6848507/6848507-fig-1-source-large.gif

- id: doi:10.1109/VLSIC.2014.6858408
  group: conference

- id: doi:10.1109/MWSYM.2015.7166871
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7155722/7166703/7166871/7166871-fig-1-source-large.gif

- id: doi:10.1109/ARFTG.2015.7162910
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7151733/7162886/7162910/7162910-fig-1-source-large.gif

- id: doi:10.1109/MWSYM.2015.7167141
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7155722/7166703/7167141/7167141-fig-1-source-large.gif

- id: doi:10.1109/VLSIC.2015.7231312
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7196579/7231231/7231312/7231312-fig-1-source-large.gif

- id: doi:10.1109/ARFTG.2015.7381458
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7372351/7381453/7381458/7381458-fig-2-source-large.gif

- id: doi:10.1109/MWSYM.2017.8058717
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8048779/8058449/8058717/8058717-fig-1-source-large.gif

- id: doi:10.1109/SIRF.2018.8304233
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8299650/8304202/8304233/8304233-fig-1-source-large.gif

- id: doi:10.1109/MWSYM.2018.8439332
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8417183/8439129/8439332/1218-fig-1-source-large.gif

- id: doi:10.1109/VLSIC.2018.8502293
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8484863/8502213/8502293/c18-1-fig-1-source-large.gif

- id: doi:10.1109/CICC.2019.8780179
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8767369/8780115/8780179/chien1-14-6-large.gif

- id: doi:10.23919/VLSIC.2019.8777991
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8766307/8777931/8777991/chien1ab-C25-2-large.gif

- id: doi:10.1109/ISSCC19947.2020.9063036
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9046640/9062887/9063036/196_2020_D26_04-fig-1-source-large.gif

- id: doi:10.1109/ARFTG54656.2022.9896578
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9896401/9896407/9896578/chien1-54656_CFP22ARG-P3-large.gif

- id: doi:10.1109/RFIC54546.2022.9863095
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9862947/9862948/9863095/9863095-fig-1-source-large.gif

- id: doi:10.1109/VLSITechnologyandCir46769.2022.9830290
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9830116/9830138/9830290/chien1-p2-chien-large.gif

- id: doi:10.1109/BioCAS54905.2022.9948586
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9948537/9948538/9948586/chien1-p4-chien-large.gif

- id: doi:10.1109/MEMS49605.2023.10052329
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/10052111/10052113/10052329/weng1-p4-weng-large.gif

- id: doi:10.1109/IMS37964.2023.10188078
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/10187888/10187785/10188078/chen5-p4-chen-large.gif

- id: doi:10.23919/VLSITechnologyandCir57934.2023.10185383
  group: conference
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/10185199/10185158/10185383/hsiao1-C8-5-large.gif


# OTHERS
- id: google.patent:US8841948B1
  group: patent

- id: google.patent:US11083388B2
  group: patent
